### ISSUE TITLE
Matomo Image Tracker not loading

### ISSUE THREAD

**Issue by bartn** [hendrikschneider/jekyll-analytics#32]
I am using this plugin to get my self-hosted matomo to be included. 
What doesn't work at the moment is the Matomo Image Tracker that is automatically included. As I have defined my personal url in the _config.yml it seems that the generated html is missing the protocol definition: http:// or https://
Currently it is requesting;
`<img src="matomo.foobar.com?idsite=1&amp;rec=1" style="border:0" alt="">`
but that results in an image not found, both in inspector as in the actual rendered webpage.

**Comment by hendrikschneider** [comment]
Thank you for reaching out to report this issue. It should be fixed now. A new release will be released soon!

**Comment by hendrikschneider** [comment]
Fixed in Version: https://rubygems.org/gems/jekyll-analytics/versions/0.1.14
