### ISSUE TITLE
Analytics code not included on Github-Page site

### ISSUE THREAD

**Issue by johnpitchko** [hendrikschneider/jekyll-analytics#5]
Added and configured plugin and `_config.yml` on localhost. Tested with `JEKYLL_ENV = production`. Analytics tag inserted correctly.

Uploaded to Github-Pages but Analytics code is not present.

Site in question is www.calgarystartupguide.com.

**Comment by johnpitchko** [comment]
Nevermind; realized this gem is not whitelisted. I am an idiot... Sorry!

**Comment by sbliven** [comment]
The README is a bit misleading when it mentions "Github pages automatically sets JEKYLL_ENV to production". While true, it is irrelevant since the gem won't run on github pages.

**Comment by zouyx** [comment]
@johnpitchko how can you set the white list?i set it but not work.

**Comment by johnpitchko** [comment]
@zouyx 

In your *_config.yml*:
```
# Plugins
whitelist: []
plugins:   []
```

See https://jekyllrb.com/docs/configuration/

**Comment by johnpitchko** [comment]
Also if you want to use additional gems/plugins on Github Pages, you need to build the site and manually upload to Github Pages. Deployment via `git push` will not work.

**Comment by zouyx** [comment]
@johnpitchko thanks ,finally i realized.......:)

**Comment by drubio1989** [comment]
@johnpitchko Do you think you could assist me by taking a look this snippet of code for my _config.yml file:

```
whitelist: [jekyll-analytics]
plugins:
  - jekyll-analytics 
```

I read the thread but I'm unclear as to what needs to be done to get the analytics to work. Is the above configuration correct? Afterwards, I executed a `jekyll build` and then `git push origin master` but analytics doesn't seem to be functioning. Is what I'm doing correct?

**Comment by danielcaldas** [comment]
@drubio1989 if you're using minima theme, as @oehme explained in #17 it will be easier to use out of the box support for GA, you just need to provide the id

**Comment by ParikhKadam** [comment]
@drubio1989 Did you get it to work? I don't even see my tracking id getting loaded when I run it on my local machine setting JEKYLL_ENV=production. I don't know why this is happening.
