### ISSUE TITLE
Piwik has been renamed to Matomo

### ISSUE THREAD

**Issue by jamietanna** [hendrikschneider/jekyll-analytics#7]
As [announced a couple of days ago](https://matomo.org/blog/2018/01/piwik-is-now-matomo/) Piwik is being rebranded to Matomo. Would it be possible to get the ability to use either the `Piwik` configuration key or the `Matomo` key? This will help with backwards compatibility, as well as allowing future users to be able to not have the confusion about Piwik vs Matomo

**Comment by hendrikschneider** [comment]
Thank you for this info, I will take a look at it

**Comment by hendrikschneider** [comment]
Matomo support added.

**Comment by jamietanna** [comment]
Amazing, thanks very much for the quick turnaround and getting these changes in!
